const SUPABASE_URL='https://jntdjewdgiotphkajjnc.supabase.co';
const SUPABASE_KEY=window.SADEEQ_SUPABASE_KEY||'';
const $=id=>document.getElementById(id);
const statusEl=$('status');
let sb=null;
const showStatus=(message,type='error')=>{statusEl.textContent=message;statusEl.className=`status show ${type}`};
const clearStatus=()=>{statusEl.textContent='';statusEl.className='status'};
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
function switchMode(mode){clearStatus();$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');$('resetForm').classList.toggle('hidden',mode!=='reset');$('updatePasswordForm').classList.toggle('hidden',mode!=='update');$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup');$('loginTab').setAttribute('aria-selected',mode==='login');$('signupTab').setAttribute('aria-selected',mode==='signup')}
function busy(form,on){const b=form.querySelector('button[type=submit]');if(!b)return;if(on){b.disabled=true;b.dataset.label=b.textContent;b.textContent='Please wait…'}else{b.disabled=false;b.textContent=b.dataset.label||b.textContent}}
async function client(){if(!SUPABASE_KEY)throw Error('Supabase publishable key is not configured.');if(sb)return sb;if(!window.supabase)throw Error('Authentication service is still loading.');sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
async function rpc(name){const c=await client();const r=await c.rpc(name);if(r.error)throw r.error;return r.data}
$('loginTab').onclick=()=>switchMode('login');
$('signupTab').onclick=()=>switchMode('signup');
$('forgotBtn').onclick=()=>switchMode('reset');
$('resetBack').onclick=()=>switchMode('login');
$('loginForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;if(!validEmail(email)||!password)return showStatus('Enter a valid email and password.');busy(f,true);try{const c=await client(),r=await c.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(!(await rpc('sadeeq_is_owner'))){await c.auth.signOut();throw Error('This account is not authorized for the owner console.')}showStatus('Login successful. Redirecting…','success');setTimeout(()=>location.href='./dashboard.html',450)}catch(err){showStatus(err.message||'Login failed. Please try again.')}finally{busy(f,false)}};
$('signupForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('signupEmail').value.trim().toLowerCase(),password=$('signupPassword').value,confirm=$('signupConfirm').value;if(!validEmail(email))return showStatus('Enter a valid email.');if(password.length<8)return showStatus('Password must be at least 8 characters.');if(password!==confirm)return showStatus('Passwords do not match.');busy(f,true);try{const c=await client();if((await rpc('sadeeq_signup_available'))!==true)return showStatus('Sign Up is closed because the owner account already exists.');const r=await c.auth.signUp({email,password});if(r.error)throw r.error;if(r.data.session){const boot=await c.rpc('sadeeq_bootstrap_owner');if(boot.error){await c.auth.signOut();throw boot.error}showStatus('Owner account created. Redirecting…','success');setTimeout(()=>location.href='./dashboard.html',450)}else showStatus('Owner account created. Check your email to confirm the account, then log in.','success')}catch(err){showStatus(err.message||'Account creation failed.')}finally{busy(f,false)}};
$('resetForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('resetEmail').value.trim().toLowerCase();if(!validEmail(email))return showStatus('Enter a valid owner email.');busy(f,true);try{const c=await client(),r=await c.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});if(r.error)throw r.error;showStatus('If this email belongs to the owner account, a secure reset link has been sent.','success')}catch(err){showStatus(err.message||'Could not send the reset link.')}finally{busy(f,false)}};
$('updatePasswordForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,password=$('newPassword').value,confirm=$('newPasswordConfirm').value;if(password.length<8)return showStatus('Password must be at least 8 characters.');if(password!==confirm)return showStatus('Passwords do not match.');busy(f,true);try{const c=await client(),s=await c.auth.getSession();if(!s.data.session)throw Error('Recovery session is missing or expired.');const r=await c.auth.updateUser({password});if(r.error)throw r.error;showStatus('Password updated successfully. You can now log in.','success');await c.auth.signOut();setTimeout(()=>switchMode('login'),900)}catch(err){showStatus(err.message||'Could not update the password.')}finally{busy(f,false)}};
(async()=>{try{const c=await client();c.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'&&session)switchMode('update')});const s=await c.auth.getSession();if(s.data.session&&await rpc('sadeeq_is_owner'))location.href='./dashboard.html'}catch(err){showStatus(err.message||'Authentication service is unavailable.')}})();
