const SUPABASE_URL=window.SADEEQ_SUPABASE_URL||'';
const SUPABASE_KEY=window.SADEEQ_SUPABASE_KEY||'';
const $=id=>document.getElementById(id);
const statusEl=$('status');
let sb=null;
let recoveryMode=false;
const showStatus=(message,type='error')=>{statusEl.textContent=message;statusEl.className=`status show ${type}`};
const clearStatus=()=>{statusEl.textContent='';statusEl.className='status'};
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const indexUrl=()=>new URL('./index.html',window.location.href).href;
function switchMode(mode){clearStatus();$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');$('resetForm').classList.toggle('hidden',mode!=='reset');$('updatePasswordForm').classList.toggle('hidden',mode!=='update');$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup');$('loginTab').setAttribute('aria-selected',mode==='login');$('signupTab').setAttribute('aria-selected',mode==='signup')}
function busy(form,on){const b=form.querySelector('button[type=submit]');if(!b)return;if(on){b.disabled=true;b.dataset.label=b.textContent;b.textContent='Please wait…'}else{b.disabled=false;b.textContent=b.dataset.label||b.textContent}}
async function client(){if(!SUPABASE_URL||!SUPABASE_KEY)throw Error('Supabase public configuration is missing.');if(sb)return sb;if(!window.supabase)throw Error('Authentication service is still loading.');sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
async function rpc(name){const c=await client();const r=await c.rpc(name);if(r.error)throw r.error;return r.data}
async function ownerCheck(){return(await rpc('sadeeq_is_owner'))===true}
$('loginTab').onclick=()=>switchMode('login');
$('signupTab').onclick=()=>switchMode('signup');
$('forgotBtn').onclick=()=>switchMode('reset');
$('resetBack').onclick=()=>switchMode('login');
$('loginForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;if(!validEmail(email)||!password)return showStatus('Enter a valid email and password.');busy(f,true);try{const c=await client(),r=await c.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(!(await ownerCheck())){await c.auth.signOut({scope:'local'});throw Error('This account is not authorized for the owner console.')}showStatus('Login successful. Redirecting…','success');window.location.replace('./dashboard.html?session=1')}catch(err){showStatus(err.message||'Login failed. Please try again.')}finally{busy(f,false)}};
$('signupForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('signupEmail').value.trim().toLowerCase(),password=$('signupPassword').value,confirm=$('signupConfirm').value;if(!validEmail(email))return showStatus('Enter a valid email.');if(password.length<8)return showStatus('Password must be at least 8 characters.');if(password!==confirm)return showStatus('Passwords do not match.');busy(f,true);try{const c=await client();const available=await rpc('sadeeq_signup_available');if(available!==true)throw Error('Sign Up is closed because the owner account already exists.');const r=await c.auth.signUp({email,password});if(r.error)throw r.error;if(r.data.user&&!r.data.session){showStatus('Owner account created. Check your email to confirm the account, then log in.','success');switchMode('login');return}if(r.data.session){if(!(await ownerCheck())){await c.auth.signOut({scope:'local'});throw Error('Owner authorization could not be established.')}showStatus('Owner account created. Redirecting…','success');window.location.replace('./dashboard.html?session=1')}else throw Error('Account creation did not complete. Please try again.')}catch(err){showStatus(err.message||'Account creation failed.')}finally{busy(f,false)}};
$('resetForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,email=$('resetEmail').value.trim().toLowerCase();if(!validEmail(email))return showStatus('Enter a valid owner email.');busy(f,true);try{const c=await client(),r=await c.auth.resetPasswordForEmail(email,{redirectTo:indexUrl()});if(r.error)throw r.error;showStatus('If this email belongs to the owner account, a secure reset link has been sent.','success')}catch(err){showStatus(err.message||'Could not send the reset link.')}finally{busy(f,false)}};
$('updatePasswordForm').onsubmit=async e=>{e.preventDefault();clearStatus();const f=e.currentTarget,password=$('newPassword').value,confirm=$('newPasswordConfirm').value;if(password.length<8)return showStatus('Password must be at least 8 characters.');if(password!==confirm)return showStatus('Passwords do not match.');busy(f,true);try{const c=await client(),s=await c.auth.getSession();if(!s.data.session||!recoveryMode)throw Error('Recovery session is missing or expired.');const r=await c.auth.updateUser({password});if(r.error)throw r.error;showStatus('Password updated successfully. You can now log in.','success');recoveryMode=false;await c.auth.signOut({scope:'local'});setTimeout(()=>switchMode('login'),900)}catch(err){showStatus(err.message||'Could not update the password.')}finally{busy(f,false)}};
(async()=>{try{const c=await client();c.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'&&session){recoveryMode=true;switchMode('update')}});const signedOut=new URLSearchParams(location.search).get('signed_out')==='1';if(signedOut){await c.auth.signOut({scope:'local'});history.replaceState(null,'',location.pathname);switchMode('login');showStatus('You have been signed out securely.','success');return}const s=await c.auth.getSession();if(s.data.session){if(await ownerCheck())window.location.replace('./dashboard.html?session=1');else await c.auth.signOut({scope:'local'})}else if(location.hash.includes('type=recovery')){recoveryMode=true;switchMode('update')}}catch(err){showStatus(err.message||'Authentication service is unavailable.')}})();
